[package]
name = "ruce_bindings"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib"]

[dependencies]
cxx = "1.0.110"

[build-dependencies]
cc = { version = "1.0", features = ["parallel"] }
walkdir = "2"
cxx-build = "1.0"